<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 
                             https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>redacted.group.id</groupId>
  <artifactId>code-style</artifactId>
  <version>${revision}${changelist}</version>
  <packaging>jar</packaging>

  <name>Code Style Definitions</name>

  <!-- ======================================================== -->
  <!-- CI-Friendly Version Properties                           -->
  <!-- ======================================================== -->
  <properties>
    <revision>0.0.1</revision>
    <changelist>-SNAPSHOT</changelist>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <!-- ============================================ -->
      <!-- Flatten Plugin                               -->
      <!-- ============================================ -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>flatten-maven-plugin</artifactId>
        <version>1.6.0</version>
        <configuration>
          <updatePomFile>true</updatePomFile>
          <flattenMode>resolveCiFriendliesOnly</flattenMode>
        </configuration>
        <executions>
          <execution>
            <id>flatten</id>
            <phase>process-resources</phase>
            <goals>
              <goal>flatten</goal>
            </goals>
          </execution>
          <execution>
            <id>flatten.clean</id>
            <phase>clean</phase>
            <goals>
              <goal>clean</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

  <!-- ======================================================== -->
  <!-- Central distribution management                          -->
  <!-- ======================================================== -->
  <distributionManagement>
    <repository>
      <id>nexus-site</id>
      <url>https://nexus.electra.lan/repository/redacted/parent-pom</url>
    </repository>
    <snapshotRepository>
      <id>nexus-snapshot</id>
      <url>https://nexus.electra.lan/repository/redacted</url>
    </snapshotRepository>
  </distributionManagement>
</project>
